### Site Settings ###
title               : Dont-code
description         : >-
                      "My applications developed automatically."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : dont-code/dont-code.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
theme: jekyll-theme-slate


### Plugins ###
plugins:
  - jemoji

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
